### ISSUE TITLE
Cannot automatically add the drives to the VM

### ISSUE THREAD

**Issue by misilot** [DavidBrenner3/VMUB#1]
I am getting the following error:

Possible reason: "MediaRegistry" section not found in the vbox file.

I am using VMUB 1.7x64 and VirtualBox 5.2.8

Thanks!

**Comment by DavidBrenner3** [comment]
Hi.

Thank you for reporting the error.

Can you please upload the vbox file (zipped if possible)  here or on a share site and post the link?

How to find the file: open a file manager (like Explorer) and go to drive C >> Users >> [Your_User_Name] >> VirtualBox VMs >> {Name _of_the_VM].
Inside there is a file with the same VM name, a blue icon and "VirtualBox Machine Definition" as Type.
If your OS is configured to see the file extension, it will appear as ".vbox".

**Comment by misilot** [comment]
[test.zip](https://github.com/DavidBrenner3/VMUB/files/1834672/test.zip)
Here it is attached

**Comment by DavidBrenner3** [comment]
Thank you.

"MediaRegistry" is a vbox file section where  informations are stored about the current drives (HDD/DVD) attached to the virtual machine.
Looks like they changed it a bit: if there are no drives the entire section is deleted (or not created in the first place).

I changed the way VMUB searches/uses this section too.
I had no problem(s) in tests but please test too to be sure.

[Virtual Machine USB Boot.x64.zip](https://github.com/DavidBrenner3/VMUB/files/1835249/Virtual.Machine.USB.Boot.x64.zip)

**Comment by misilot** [comment]
Thanks this fixed the issue!

**Comment by DavidBrenner3** [comment]
Issue officially solved in latest release.

**Comment by azrailkenan61** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/99977016/222267892-a88761f1-8ff0-4c4a-a1b7-b4006d82a3bc.png)

**Comment by mawais22** [comment]
![](https://user-images.githubusercontent.com/99977016/222267892-a88761f1-8ff0-4c4a-a1b7-b4006d82a3bc.png)
apko iska salotion mil gya hay kya?
same problem heare.
what is salotion?

**Comment by mawais22** [comment]
![](https://user-images.githubusercontent.com/99977016/222267892-a88761f1-8ff0-4c4a-a1b7-b4006d82a3bc.png)
salotion>

**Comment by steve6375** [comment]
VMUB is for VBox v5 only.
