### ISSUE TITLE
--startvm is an option for the VirtualBox VM runner (VirtualBoxVM) application, not the VirtualBox Manager.

### ISSUE THREAD

**Issue by xahon** [DavidBrenner3/VMUB#10]
When starting with the "Start" button
Both virtualbox and that app opened with admin rights

However, I noticed that when I click start it doesn't use existing VirtualBox instance. It shows that message and opens another instance of vbox

**Comment by steve6375** [comment]
Virtual Box 5 must be used
Virtual Box 6 is not supported.

**Comment by xahon** [comment]
@steve6375 thanks for the quickest reply i ever saw on github. I'll try to downgrade

*UPD*
Yes, it was the reason

For those, who encountered the same issue:
1. Latest Virtualbox 5.x listing (https://www.virtualbox.org/wiki/Download_Old_Builds_5_2)
2. If you missing VTx/AMD-v settings (64 bit OS in the list of Virtualbox) then do everything written on the [page](https://forums.virtualbox.org/viewtopic.php?t=86449) (For me personally x64 support was fixed after the latter step with cold boot, I didn't hope that all these steps help me)

**Comment by ElhanM** [comment]
Try VirtualBoxVM --startvm "My Operating System" &
