### ISSUE TITLE
No bootable System Found System halted on "Portable VirtualBox" With Easy2boot USB DRive

### ISSUE THREAD

**Issue by tathastu871** [DavidBrenner3/VMUB#13]
_PortableVBOX_ (https://www.vbox.me/files/Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe)
**Location:** C:\Users\T\Desktop\Vbox\Portable-VirtualBox\
**Preferences MachineFolder:** C:\Users\T\Desktop\Vbox

_VMUB_
Location: 
Tried Both 
ON Easy2boot Drive: F:\Vmub
As well as Desktop

Options: EXE Path: C:\Users\T\Desktop\Vbox\Portable-VirtualBox\Portable-VirtualBox.exe
VM Path: C:\Users\T\Desktop\Vbox\Boot\Boot.vbox

Above are my configurations:
But booting isnt happening.

Same config work when i use installed Vbox
But notwith Portable Vbox

**Comment by steve6375** [comment]
VMUB should not be on the E2B drive
VBOX should not be on the E2B drive
when you click Start in VMUB it dismounts the USB drive from Windows so VBOX can lock it and have full access.

**Comment by tathastu871** [comment]
> VMUB should not be on the E2B drive VBOX should not be on the E2B drive when you click Start in VMUB it dismounts the USB drive from Windows so VBOX can lock it and have full access.

I placed both VMUB and PortableVbox on desktop not on USB
Even Placing VMUB on usb drive works when installed VBOX is used but not with Portable one

**Comment by steve6375** [comment]
Then why do you say:
```
VMUB
Location: ON Easy2boot Drive: F:\Vmub
```
???

**Comment by tathastu871** [comment]
> Then why do you say:
> 
> ```
> VMUB
> Location: ON Easy2boot Drive: F:\Vmub
> ```
> 
> ???

Updated OK...

**Comment by tathastu871** [comment]
Following  Config Works:

**Both VBOX AND VMUB ON USB DRIVE**

Vmub: F:\Virtual.MachineUSBBoot\Virtual Machine USB Boot.x64.exe
PortableVbox: F:\PortableVbox\Portable-VirtualBox\Portable-VirtualBox.exe

**Copy the Existing Vbox Machine From host to Usb drive:**
Eg. Copy "C:\Users\T\Viryal Vms\Boot" Folder to F:\Boot

**Open  F:\PortableVbox\Portable-VirtualBox\Portable-VirtualBox.exe**
Preferences ---> DefaultMachineFolder ---> F:\
Click Add and add F:\Boot\Boot.vbox

**Open F:\Virtual.MachineUSBBoot\Virtual Machine USB Boot.x64.exe**
Options ---> PortableBox ---> EXE PATH : F:\PortableVbox\Portable-VirtualBox\Portable-VirtualBox.exe
Options ---> Uncheck Use already loaded dlls/drivers/services
Add ---->Mode to Load VM --->VM Path ---> Add F:\Boot\Boot.vbox in Path
Then 
CTRL+START To Prevent Locking Of Usb
