### ISSUE TITLE
How to use with portable version of virtualbox

### ISSUE THREAD

**Issue by Doerthous** [DavidBrenner3/VMUB#7]
## Issue
I want to use VMUB with a portable virtualbox,  but I can't add an instance of VMUB because it cannot detect the virtualbox. Then I try the "VM path" option, and get the following message:

![image](https://user-images.githubusercontent.com/16850562/66901432-439df580-f031-11e9-8ddb-a546a1b3a0dc.png)

can somebody help?

## Environment
virtualbox 6.0
vmub 1.7.2 (portable x86)
win 10

**Comment by steve6375** [comment]
VMUB does not work with VBox 6. Use VBox 5.

**Comment by Doerthous** [comment]
I cannot run VBox 5 using portable-virtualbox.

I download the VirtualBox-5.2.34-133893-Win.exe, and use Portable-VirtualBox.exe to extract the VBox, then I try to run the Portable-VirtualBox.exe, it just exit immediately. so as the VirtualBox.exe in the app32/ folder.

I can run VBox6 with an installed-version, for convenience, I want to use the portable version of VBox.

Is there anything wrong when I use VBox or VMUB? I a newer of VBox.

**Comment by Doerthous** [comment]
I think, the VMUB was take $HOME/VirtualBox VMs as the search place for vm, but the portable vbox put all vm inside another data folder locate with the portable vbox home. And This two folder are not the same.

It seems that VMUB always try to find vms in $HOME/VirtualBox VMs, even if I use the "vm path" option of VMUB. Is there anyway to change the path?

**Comment by steve6375** [comment]
VBox 6 wont work with VMUB 1.7.2 because VBOX 6 uses different run-time exe files.

If you use VMUB with VBOX 6 you will get an error 

> '--startvm is an option for the VirtualBox VM runner'

so even if you fix the VM folder issue, you will hit this error next and VMUB will not work.
You need to try to get VBOX 5 working first. I have never tried portable versions so I don't know if they work or not, but I think some people have used it OK and David B would have tested it.

**Comment by Doerthous** [comment]
Yes I get the error though, the VBox was still start with the vm no running. So I need to start vm manually everytime. Now I reinstall the VBox6, and give up the portable version.
