### ISSUE TITLE
Cannot automatically add the drives to the Virtual Box

### ISSUE THREAD

**Issue by tajamulsheeraz** [DavidBrenner3/VMUB#9]
Hi David,

Greetings!

I am getting the below mentioned error. Please Advice!

I tried using in C drive: [USB1.zip](https://github.com/DavidBrenner3/VMUB/files/4725114/USB1.zip)
I tried using in E drive(Pen drive): [USB2-linking.zip](https://github.com/DavidBrenner3/VMUB/files/4725118/USB2-linking.zip)

![image](https://user-images.githubusercontent.com/17013846/83668807-2fbdf880-a5ee-11ea-90d5-10c737d6a03b.png)

Thanks & Regards,
Tajamul Sheeraz

**Comment by steve6375** [comment]
Are you running as Administrator? Are you using VBOX v5?

**Comment by Drift91** [comment]
VBox v6 came out nearly two years ago. Is it not being supported?

**Edit:**
I should mention I'm having the same issue on VBox 6.1.14.

**Comment by steve6375** [comment]
This is an open source project. You are welcome to update it for VBox v6.
